version: '3.5'
services:
  php:
    build:
      context: ./docker/php
      args:
        uid: ${UID}
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - "network"

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
    networks:
      backend:
        aliases:
          - "network"

#  nuxt:
#    image: node:14.15.5
#    command: yarn dev
#    volumes:
#      - ./nuxt:/usr/src/app
#    working_dir: /usr/src/app
#    ports:
#      - "3000:3000"
#    environment:
#      HOST: 0.0.0.0

networks:
  backend:
    name: backend-network